import Database from "better-sqlite3";
import { AdapterContract, AdapterTarget, RenderedOutput } from "./contract.js";
import { hashContent } from "../../lib/hashing.js";
import { writeFileSync, mkdirSync, existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

export function createCursorAdapter(db: Database.Database): AdapterContract {
  const platform = "cursor";

  function materializeRules(content: string): string[] {
    return content
      .split("\n\n")
      .map((rule) => rule.trim())
      .filter(Boolean);
  }

  function resolveTargets(ownerType: string, ownerId: number): AdapterTarget[] {
    const targets: AdapterTarget[] = [];

    if (ownerType === "project") {
      const project = db.prepare("SELECT root_path FROM governed_projects WHERE id = ?").get(ownerId) as any;
      if (project) {
        targets.push({
          platform,
          targetPath: resolve(project.root_path, ".cursor", "rules"),
          artifactType: "cursor_rules_dir",
        });
      }
    }

    return targets;
  }

  function render(policyContent: string, standardFiles: { relativePath: string; content: string }[]): RenderedOutput {
    const renderedFiles: string[] = [];

    for (const file of standardFiles) {
      const ruleName = file.relativePath.replace(/\.(md|mdc)$/, "").replace(/[^a-zA-Z0-9_-]/g, "-");
      const mdcContent = [
        "---",
        `description: ${ruleName} — generated by AI Rules Manager`,
        "---",
        "",
        file.content.trim(),
      ].join("\n");
      renderedFiles.push(mdcContent);
    }

    // Add policy content as additional rule
    if (policyContent) {
      const policyMdc = [
        "---",
        "description: Project-specific rules — generated by AI Rules Manager",
        "---",
        "",
        policyContent.trim(),
      ].join("\n");
      renderedFiles.push(policyMdc);
    }

    return {
      platform,
      content: renderedFiles.join("\n\n"),
      targets: [],
    };
  }

  function validate(output: RenderedOutput): string[] {
    const errors: string[] = [];
    if (!output.content || output.content.trim().length === 0) {
      errors.push("Empty rendered content");
    }
    return errors;
  }

  async function write(targets: AdapterTarget[], output: RenderedOutput): Promise<{ written: string[]; errors: string[] }> {
    const written: string[] = [];
    const errors: string[] = [];
    const rules = materializeRules(output.content);

    for (const target of targets) {
      try {
        mkdirSync(target.targetPath, { recursive: true });
        for (let i = 0; i < rules.length; i++) {
          const ruleContent = rules[i];
          if (!ruleContent) continue;
          const ruleName = `rule-${i + 1}`;
          const filePath = resolve(target.targetPath, `${ruleName}.mdc`);
          writeFileSync(filePath, ruleContent, "utf-8");
          written.push(filePath);
        }
      } catch (e: any) {
        errors.push(`${target.targetPath}: ${e.message}`);
      }
    }

    return { written, errors };
  }

  async function verify(targets: AdapterTarget[], expectedHash: string): Promise<{ targetPath: string; match: boolean }[]> {
    return targets.map((t) => {
      try {
        if (!existsSync(t.targetPath)) return { targetPath: t.targetPath, match: false };
        const files = readdirSyncSimple(t.targetPath)
          .filter((n) => n.endsWith(".mdc"))
          .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
        const combined = files.map((f) => readFileSync(resolve(t.targetPath, f), "utf-8").trim()).join("\n\n");
        const actualHash = hashContent(combined);
        return { targetPath: t.targetPath, match: actualHash === expectedHash };
      } catch {
        return { targetPath: t.targetPath, match: false };
      }
    });
  }

  return { platform, resolveTargets, render, validate, write, verify };
}

function readdirSyncSimple(dir: string): string[] {
  try { return readdirSync(dir); } catch { return []; }
}
