#Requires -Version 5.1
<#
.SYNOPSIS
  Start AI Rules Manager (Windows).

.DESCRIPTION
  Detects fixed drive letters, generates compose.drives.yaml,
  writes a minimal .env if missing, then runs docker compose up.

  New user:
    git clone https://github.com/mcandiav/ai-rules-manager.git
    cd <folder>
    .\start.ps1
#>
$ErrorActionPreference = "Stop"

$RepoRoot = $PSScriptRoot
Set-Location $RepoRoot

function Get-FixedDriveLetters {
  Get-PSDrive -PSProvider FileSystem |
    Where-Object {
      $_.Root -match '^[A-Za-z]:\\$' -and
      (Test-Path -LiteralPath $_.Root)
    } |
    Sort-Object Name |
    ForEach-Object { $_.Name.ToUpperInvariant() }
}

$drives = @(Get-FixedDriveLetters)
if ($drives.Count -eq 0) {
  throw "No fixed drives detected. Cannot mount host paths into Docker."
}

$userProfile = ($env:USERPROFILE -replace "\\", "/").TrimEnd("/")
if (-not $userProfile) {
  throw "USERPROFILE is empty. Cannot resolve Windows user home."
}

$volumeLines = New-Object System.Collections.Generic.List[string]
$mappingParts = New-Object System.Collections.Generic.List[string]

foreach ($letter in $drives) {
  $hostRoot = "${letter}:/"
  $containerRoot = "/host/$($letter.ToLowerInvariant())"
  $volumeLines.Add("      - ${hostRoot}:${containerRoot}")
  $mappingParts.Add("${hostRoot}:${containerRoot}")
}

$driveMappings = [string]::Join(";", $mappingParts)
$projectName = Split-Path -Leaf $RepoRoot

$drivesFile = Join-Path $RepoRoot "compose.drives.yaml"
$drivesYaml = @"
# Generated by start.ps1 — do not edit by hand.
# Remounts all fixed Windows drives so any project path can be governed.
services:
  api:
    volumes:
$($volumeLines -join "`n")
    environment:
      - HOST_DRIVE_MAPPINGS=$driveMappings
      - HOST_HOME_ROOT=$userProfile
"@
Set-Content -Path $drivesFile -Value $drivesYaml -Encoding utf8

$envFile = Join-Path $RepoRoot ".env"
if (-not (Test-Path -LiteralPath $envFile)) {
  $envContent = @"
COMPOSE_PROJECT_NAME=$projectName
API_PORT=8002
WEB_PORT=3002
POLL_INTERVAL_MS=30000
NODE_ENV=production
HOST_HOME_ROOT=$userProfile
HOST_DRIVE_MAPPINGS=$driveMappings
"@
  Set-Content -Path $envFile -Value $envContent -Encoding utf8
  Write-Host "Created .env with ports 8002/3002 and USERPROFILE home."
} else {
  $existing = Get-Content -LiteralPath $envFile -Raw
  if ($existing -notmatch "(?m)^HOST_HOME_ROOT=") {
    Add-Content -LiteralPath $envFile -Value "HOST_HOME_ROOT=$userProfile"
  }
  if ($existing -match "(?m)^HOST_DRIVE_MAPPINGS=.*$") {
    $existing = [regex]::Replace($existing, "(?m)^HOST_DRIVE_MAPPINGS=.*$", "HOST_DRIVE_MAPPINGS=$driveMappings")
    Set-Content -LiteralPath $envFile -Value $existing.TrimEnd() -Encoding utf8
  } else {
    Add-Content -LiteralPath $envFile -Value "HOST_DRIVE_MAPPINGS=$driveMappings"
  }
}

Write-Host "Mounting drives: $($drives -join ', ')"
Write-Host "Host home: $userProfile"
Write-Host "Starting Docker Compose..."

docker compose -f compose.yaml -f compose.drives.yaml up -d --build
if ($LASTEXITCODE -ne 0) {
  throw "docker compose failed with exit code $LASTEXITCODE"
}

Write-Host ""
Write-Host "OK. UI: http://localhost:3002  |  API: http://localhost:8002"
Write-Host "If a drive is missing inside the container, share it in Docker Desktop > Settings > Resources > File sharing."
